networks:
  orders-net:
    driver: bridge

services:
  orders-api:
    image: docker-lab/orders-api:latest
    container_name: backend-orders-api
    build:
      context: .
    # ports:
    #   - "8081:8080"
    environment:
      SOME_ENV_VAR: "some value"
      DEBUG: true
    env_file: ".env"
    networks:
      - orders-net

  orders-web:
    image: orders-frontend
    container_name: frontend-orders
    build:
      context: frontend
    ports:
      - "3001:3000"
    environment:
      BACKEND_HOST: orders-api
      # BACKEND_PORT: 8080
    networks:
      - orders-net
