networks:
  orders-net:
    driver: bridge

volumes:
  appdata: {}

services:
  orders-api:
    image: docker-lab/orders-api:latest
    container_name: backend-orders-api
    build:
      context: .
    ports:
      - "8081:8080"
    environment:
      DB_PATH: /data/orders.db
      DEBUG: true
    env_file: ".env"

  orders-web:
    image: orders-frontend
    container_name: frontend-orders
    build:
      context: frontend
    ports:
      - "3001:3000"
    environment:
      BACKEND_HOST: orders-api
      # BACKEND_PORT: 8080
    networks:
      - orders-net
