FROM python:3.11

WORKDIR /app
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt &&     apt-get update && apt-get install -y --no-install-recommends curl &&     rm -rf /var/lib/apt/lists/*
COPY app /app

CMD ["gunicorn", "-b", "0.0.0.0:8080", "app:app"]
