version: "3.8"
name: docker-lab

services:
  orders-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-lab/orders-api:optimized
    container_name: orders-api
    environment:
      DB_PATH: /data/orders.db
    volumes:
      - appdata:/data
    ports:
      - "8083:8080"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  appdata: {}
