services:
  orders-api:
    image: docker-lab/orders-api:latest
    container_name: backend-orders-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      DB_PATH: /data/orders.db
      DEBUG: true
    env_file: ".env"
