apiVersion: v1
kind: Namespace
metadata:
  name: docker-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: docker-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: docker-lab/orders-api:optimized
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_PATH
              value: /data/orders.db
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: appdata
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: appdata
          emptyDir: {} # dev only; use PVC in prod
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api
  namespace: docker-lab
spec:
  selector:
    app: orders-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
      name: http
  type: NodePort
